### PR TITLE
Add linux aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel support.
Related to #53 . @aflc Please review the changes.

### CODE REVIEW

**Comment by odidev** [comment]
@aflc, could you please take a look into this PR? Thanks in advance.

**Comment by odidev** [comment]
@aflc, could you please take a look into this PR? Thanks in advance.

**Comment by odidev** [comment]
@aflc, could you please take a look into this PR?

**Comment by roy-ht** [comment]
@odidev I released 0.6.0. Please check it working as expected. Thanks!

**Comment by odidev** [comment]
Linux AArch64 wheels release on PyPI. this PR is not required any more. Closing it.

**Pull request closed without merging**
